// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC237sBj644ew1A_mAr63fOvoomICRqqac',
    appId: '1:810758968068:web:beb61d04765708e77cf651',
    messagingSenderId: '810758968068',
    projectId: 'sign-bf771',
    authDomain: 'sign-bf771.firebaseapp.com',
    storageBucket: 'sign-bf771.appspot.com',
    measurementId: 'G-KCBL0FEM90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvYWAXBMYvq_2WrZLyDNI3Kw1K0h70TAo',
    appId: '1:810758968068:android:a3addf4e72a16fa57cf651',
    messagingSenderId: '810758968068',
    projectId: 'sign-bf771',
    storageBucket: 'sign-bf771.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmkJfpTvAKuiw7MvtZPINLNehAE6cg5wc',
    appId: '1:810758968068:ios:98e8d6f87c5346b17cf651',
    messagingSenderId: '810758968068',
    projectId: 'sign-bf771',
    storageBucket: 'sign-bf771.appspot.com',
    androidClientId: '810758968068-nsul1rsik4h1q7lsthnv3335gqru9bds.apps.googleusercontent.com',
    iosClientId: '810758968068-dkpd1ngrs79ngtsa3n2hh31oc0cdbk1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.signGoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmkJfpTvAKuiw7MvtZPINLNehAE6cg5wc',
    appId: '1:810758968068:ios:98e8d6f87c5346b17cf651',
    messagingSenderId: '810758968068',
    projectId: 'sign-bf771',
    storageBucket: 'sign-bf771.appspot.com',
    androidClientId: '810758968068-nsul1rsik4h1q7lsthnv3335gqru9bds.apps.googleusercontent.com',
    iosClientId: '810758968068-dkpd1ngrs79ngtsa3n2hh31oc0cdbk1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.signGoogle',
  );
}
